---
- name: Construct ketchup_nginx
  hosts: "ketchup_nginx"
  gather_facts: True
  vars:
    packages_el_nginx_packages: True
  tasks:
    - name: Enable epel repository
      include_role: name=repos_el tasks_from=main
    - name: Install packages
      include_role: name=packages_el tasks_from=main
    - name: Configure Nginx
      include_role: name=nginx tasks_from=main

- name: Test ketchup_nginx
  hosts: "ketchup_nginx"
  gather_facts: True
  vars:
    packages_el_nginx_packages: True
  tasks:
    - name: Unit Test - Enable epel repository
      include_role: name=repos_el tasks_from=unit_test
    - name: Unit Test - Install packages
      include_role: name=packages_el tasks_from=unit_test
    - name: Unit Test - Configure Nginx
      include_role: name=nginx tasks_from=unit_test
