---
- hosts: "ketchup"
  gather_facts: true
  tasks:
    - name: Exec repos_el role
      include_role:
        name: repos_el
        tasks_from: main

    - name: Unit Test for repos_el role
      include_role:
        name: repos_el
        tasks_from: unit_test
