---
- name: Cleanup Ketchup host
  hosts: "ketchup"
  gather_facts: true

  roles:
    - role: cleanup_ketchup


- name: Cleanup Nginx frontend for Ketchup
  hosts: "ketchup_nginx"
  roles:
    - role: cleanup_nginx
